const baseWords = [
  "adoc",
  "antipattern",
  "asciidoc",
  "asciidoctor",
  "befores",
  "behaviour",
  "behavioural",
  "conformances",
  "crdt",
  "daemonized",
  "deinitialize",
  "deinitialized",
  "dists",
  "dtos",
  "exfiltrate",
  "exfiltration",
  "favorited",
  "githubusercontent",
  "granularities",
  "grdb",
  "groq",
  "healthz",
  "icrm",
  "ifdef",
  "ifndef",
  "inlines",
  "iphoneos",
  "jank",
  "mgmt",
  "mkdir",
  "mkdirs",
  "multiplatform",
  "mvvm",
  "neue",
  "nocaseglob",
  "nullglob",
  "objs",
  "pbxproj",
  "pref",
  "prefs",
  "println",
  "printlns",
  "rdbms",
  "revealjs",
  "revealjsdir",
  "serde",
  "simctl",
  "swarch",
  "swiftui",
  "tappable",
  "toclevels",
  "unfavorite",
  "unfavorited",
  "unlog",
  "unlogged",
  "upsert",
  "upserts",
  "upserted",
  "upserting",
  "vandervoort",
  "weeknotes",
  "wireframes",
  "xcasset",
  "xcassets",
  "xcconfig",
  "xcodeproj",
  "xcrun",
  "xctrace",
  "xcworkspace",
  "xunit",
];

export default {
  // Version of the setting file.  Always 0.2
  version: "0.2",
  // language - current active spelling language
  language: "en",
  // words - list of words to be always considered correct
  words: baseWords,
  ignorePaths: [
    "vscode-extension",
    ".git/{info,lfs,logs,refs,objects}/**",
    ".git/{index,*refs,*HEAD}",
    ".gitignore",
    ".vscode",
    ".vscode-insiders",
    "**/node_modules",
    "**/package.json",
    "**/package-lock.json",
    "**/test_*",
    "**/project.pbxproj",
    "cspell.config.js",
    "cspell.config.mjs",
  ],
  languageSettings: [
    {
      languageId: "javascript,typescript,javascriptreact,typescriptreact",
      locale: "*",
      words: [
        ...baseWords,
        "tabular-nums", // Tailwind
        "uuidv",
        "valierror",
      ],
    },
    {
      languageId: "swift",
      locale: "*",
      words: [
        ...baseWords,
        "fileprivate",
        "inout",
        "swiftlint",
        "swiftui",
        "xcui",
        "xcuiautomation",
        "xmark",
      ],
    },
    {
      languageId: "yaml",
      locale: "*",
      words: [...baseWords, "temurin"],
    },
    {
      languageId: "asciidoc,markdown",
      locale: "*",
      words: [
        ...baseWords,
        "fileprivate",
        "inout",
        "sectnums",
        "swiftlint",
        "swiftui",
        "uuidv",
        "valierror",
        "xcui",
        "xcuiautomation",
        "xmark",
      ],
    },
  ],
  // flagWords - list of words to be always considered incorrect
  // This is useful for offensive words and common spelling errors.
  // For example "hte" should be "the"
  flagWords: [],
  allowCompoundWords: true,
  dictionaries: [
    "bash",
    "css",
    "html",
    "node",
    "npm",
    "python",
    "softwareTerms",
    "typescript",
  ],
};
